version: "3.8"

services:
  mysql:
    image: mysql:8.0.40
    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: Ritesh@123
      MYSQL_DATABASE: ecomdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Ritesh@123
    ports:
      - "8081:80"
    depends_on:
      - mysql

  springboot:
    build: .
    container_name: my_ecomm_project
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ecomdb
      DB_USERNAME: root
      DB_PASSWORD: Ritesh@123
    ports:
      - "8082:8080"
    depends_on:
      - mysql

volumes:
  db_data:
